version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres-2
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  nats-streaming:
    image: nats-streaming
    container_name: nats-1
    restart: on-failure
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  db-data: